# This is a general use makefile for robotics cape projects written in C.
# Just change the target name to match your main source code filename.
TARGET = test_filters

include /usr/include/robotics.mk 
