#!/bin/sh
 
# Exit on error
set -e
 
# Source debconf library.
. /usr/share/debconf/confmodule

# check model
MODEL="$(cat /proc/device-tree/model)"
ISBLACK=false
ISBLUE=false
if [ "$MODEL" = "TI AM335x BeagleBone Blue" ]; then
	ISBLUE=true
elif [ "$MODEL" = "TI AM335x BeagleBone Black" ]; then
	ISBLACK=true
elif [ "$MODEL" = "TI AM335x BeagleBone Black Wireless" ]; then
	ISBLACK=true
fi

# if not running in noninteractive mode, ask some questions
if [ ! "$DEBIAN_FRONTEND" = "noninteractive" ]; then

	# first, for Black and Black wireless we need to ask to modify uEnv.txt
	if [ "$ISBLACK" = "true" ]; then
		db_input critical roboticscape/q_enable_dt || true
		db_go || true
	fi

	# if blue or black, ask for what should run on boot
	if [ "$ISBLACK" = "true" ] || [ "$ISBLUE" = "true" ]; then
		db_input critical roboticscape/q_runonboot || true
		db_go || true
	fi
fi


