#!/bin/sh


# ld config to make sure libroboticscape.so is recognized
ldconfig

# enable services
echo "systemctl daemon-reload"
systemctl daemon-reload
echo "Enabling battery_monitor Service"
systemctl enable battery_monitor
echo "Starting battery_monitor Service"
systemctl start battery_monitor
echo "Enabling roboticscape Service"
systemctl enable roboticscape


# startup program question
echo "Sourcing debconf Library"
set -e
. /usr/share/debconf/confmodule

echo "Getting roboticscape/question1"
db_get roboticscape/question1
PROG=$RET

echo "user selected $PROG"

if [ "$PROG" = "blink" ]; then
	ln -s -f /usr/bin/blink /etc/roboticscape/link_to_startup_program
elif  [ "$PROG" = "balance" ]; then
	ln -s -f /usr/bin/balance /etc/roboticscape/link_to_startup_program
elif  [ "$PROG" = "none" ]; then
	ln -s -f /usr/bin/bare_minimum /etc/roboticscape/link_to_startup_program
fi


echo "Configuring Device Tree"
configure_robotics_dt.sh
echo "Done Configuring Device Tree"



echo " "
echo " "
echo " "
echo "Robotics Cape package installation complete."
echo "Please reboot now."
echo " "

exit 0