#!/bin/sh

# ld config to make sure libroboticscape.so is recognized
ldconfig

# start the battery monitor service
systemctl daemon-reload
systemctl enable battery_monitor
systemctl start battery_monitor

# Source debconf library.
set -e
. /usr/share/debconf/confmodule
 
# Fetching configuration from debconf
# for answer to startup program
db_get roboticscape/question1
PROG=$RET

echo "user selected $PROG"

if [ "$PROG" = "blink" ]; then
	ln -s -f /usr/bin/blink /etc/roboticscape/link_to_startup_program
elif  [ "$PROG" = "balance" ]; then
	ln -s -f /usr/bin/balance /etc/roboticscape/link_to_startup_program
elif  [ "$PROG" = "none" ]; then
	ln -s -f /usr/bin/bare_minimum /etc/roboticscape/link_to_startup_program
fi

systemctl enable roboticscape

echo " "
echo " "
echo " "
echo "roboticscape Package Installed"
echo "If you are not on a Bealgebone Blue, please"
echo "run configure_robotics_overlay.sh once to configure the"
echo "overlay, then reboot to load device tree. After rebooting"
echo "we suggest running calibrate_gyro and calibrate_mag."

exit 0