#!/bin/sh

# don't put anything before here or it will break debconf!
# Source debconf library.
set -e
. /usr/share/debconf/confmodule
 
if [ ! "$DEBIAN_FRONTEND" = "noninteractive" ] ; then
	# Fetching configuration from debconf
	# for answer to startup program
	db_get roboticscape/question1
	PROG=$RET
fi

echo "user selected $PROG"

if [ ! -d "/etc/roboticscape" ]; then
  echo "making /etc/roboticscape"
  mkdir /etc/roboticscape
fi

if [ ! "$DEBIAN_FRONTEND" = "noninteractive" ] ; then
	if [ "$PROG" = "rc_blink" ]; then
		ln -s -f /usr/bin/rc_blink /etc/roboticscape/link_to_startup_program
	elif  [ "$PROG" = "rc_balance" ]; then
		ln -s -f /usr/bin/rc_balance /etc/roboticscape/link_to_startup_program
	elif  [ "$PROG" = "none" ]; then
		ln -s -f /usr/bin/rc_bare_minimum /etc/roboticscape/link_to_startup_program
	else
		echo "invalid answer to question"
		exit 1
	fi

	# enable roboticscape service
	echo "systemctl daemon-reload"
	systemctl daemon-reload
	echo "Enabling roboticscape Service"
	systemctl enable roboticscape

	# enable rc_battery_monitor
	echo "Enabling rc_battery_monitor Service"
	systemctl enable rc_battery_monitor
	echo "Starting rc_battery_monitor Service"
	systemctl start rc_battery_monitor

	echo "Configuring Device Tree"
	configure_robotics_dt.sh
	echo "Done Configuring Device Tree"



	echo " "
	echo " "
	echo " "
	echo "Robotics Cape package installation complete."
	echo "Please reboot now."
	echo " "
fi

exit 0
