#!/bin/sh

systemctl daemon-reload

if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi

#DEBHELPER#

echo "librobotcontrol Package Uninstallation Complete"

exit 0

