#!/bin/sh

systemctl daemon-reload

. /usr/share/debconf/confmodule
db_purge

if [ "$1" = "remove" ]; then
	# just removed so library, so need to run ldconfig
	ldconfig
fi

echo "Uninstallation Complete"

exit 0

