#!/bin/sh

SERVICE_DIR=/lib/systemd/system
BATT_SERVICE=rc_battery_monitor
ROBOT_SERVICE=roboticscape

if [ -f "$SERVICE_DIR/$BATT_SERVICE.service" ]
then
  systemctl stop $BATT_SERVICE
fi

if [ -f "$SERVICE_DIR/$ROBOT_SERVICE.service" ]
then
  systemctl stop $ROBOT_SERVICE
fi

exit 0
