#!/bin/sh


# stop and disable the battery monitor service
systemctl stop rc_battery_monitor
systemctl disable rc_battery_monitor

# stop and disable the roboticscape service
systemctl stop roboticscape
systemctl disable roboticscape

exit 0
