all:
	cd balance; $(MAKE)
	cd bare_minimum; $(MAKE)
	cd battery_monitor; $(MAKE)
	cd bind_dsm2; $(MAKE)
	cd blink; $(MAKE)
	cd calibrate_dsm2; $(MAKE)
	cd calibrate_escs; $(MAKE)
	cd calibrate_gyro; $(MAKE)
	cd complementary_filter; $(MAKE)
	cd fly; $(MAKE)
	cd kill_robot; $(MAKE)
	cd mmap_eqep; $(MAKE)
	cd test_dsm2; $(MAKE)
	cd test_encoders; $(MAKE)
	cd test_imu; $(MAKE)
	cd test_mavlink; $(MAKE)
	cd test_motors; $(MAKE)
	cd test_servos; $(MAKE)
	

clean:
	cd balance; $(MAKE) clean
	cd bare_minimum; $(MAKE) clean
	cd battery_monitor; $(MAKE) clean
	cd bind_dsm2; $(MAKE) clean
	cd blink; $(MAKE) clean
	cd calibrate_dsm2; $(MAKE) clean
	cd calibrate_escs; $(MAKE) clean
	cd calibrate_gyro; $(MAKE) clean
	cd complementary_filter; $(MAKE) clean
	cd fly; $(MAKE) clean
	cd kill_robot; $(MAKE)clean
	cd mmap_eqep; $(MAKE) clean
	cd test_dsm2; $(MAKE) clean
	cd test_encoders; $(MAKE) clean
	cd test_imu; $(MAKE) clean
	cd test_mavlink; $(MAKE) clean
	cd test_motors; $(MAKE) clean
	cd test_servos; $(MAKE) clean
	
install:
	cd balance; $(MAKE) install
	cd bare_minimum; $(MAKE) install
	cd battery_monitor; $(MAKE) install
	cd bind_dsm2; $(MAKE) install
	cd blink; $(MAKE) install
	cd calibrate_dsm2; $(MAKE) install
	cd calibrate_escs; $(MAKE) install
	cd calibrate_gyro; $(MAKE) install
	cd complementary_filter; $(MAKE) install
	cd fly; $(MAKE) install
	cd kill_robot; $(MAKE) install
	cd mmap_eqep; $(MAKE) install
	cd test_dsm2; $(MAKE) install
	cd test_encoders; $(MAKE) install
	cd test_imu; $(MAKE) install
	cd test_mavlink; $(MAKE) install
	cd test_motors; $(MAKE) install
	cd test_servos; $(MAKE) install
